### ISSUE TITLE
怎么使用你的文件应用到订阅连接？非常感谢指点一下，怎么转换。

### ISSUE THREAD

**Issue by garydak** [Wyatt323/openclash-rules#1]

**Comment by Wyatt323** [comment]
参考这个
https://api.dler.io/sub?target=Clash&url=你的订阅链接（URL编码）&config=https%3A%2F%2Fraw.githubusercontent.com%2FWyatt323%2Fopenclash-rules%2Fmain%2FACL4SSR_Online_Full.ini

**Comment by garydak** [comment]
用以上这个连接替换掉订阅连接就自动更新你的项目吗？
非常感谢

**Comment by Wyatt323** [comment]
理论上是这样的，我没用过这种形式，我都是放在订阅转换站里用的，晚点我做个订阅转换站，把这个配置放进去

**Comment by garydak** [comment]
试了刷不出来订阅连接，但是wgetnz 的那个连接方式可以顺利订阅https://api.dler.io/sub?target=clash&new_name=true&url=你的订阅链接（URL编码）&config=https%3A%2F%2Fraw.githubusercontent.com%2Fwgetnz%2Fchatgpt%2Fmain%2FFull.ini，但是感觉方式是一样的呀，很奇怪。用他的连接你的config-你的路径就可以成功订阅。

**Comment by Wyatt323** [comment]
可能是因为我没有new_name这个参数，解决了就行
