### ISSUE TITLE
今天更新过以后 openclash 启动失败

### ISSUE THREAD

**Issue by garydak** [Wyatt323/openclash-rules#2]
![image](https://user-images.githubusercontent.com/76925210/225482909-b92e06bb-e11c-420e-802a-7a9bf295a7c0.png)

**Comment by Wyatt323** [comment]
试了一下，没问题，建议删除配置文件，重新转换一下订阅

**Comment by garydak** [comment]
谢谢已经搞定了，还是AdGuard 那里出的问题
