### ISSUE TITLE
能不能处理一下专门针对bing new 设定一个规则

### ISSUE THREAD

**Issue by garydak** [Wyatt323/openclash-rules#3]
目前一直指向cn.bing.com，造成了很过国内朋友的困惑。无法访问bing new ，chat 无法访问。

**Comment by Wyatt323** [comment]
我目前也进不去，可以的话你可以抓包一下，进去会用到哪些域名

**Comment by garydak** [comment]
你是要正常进入bing chat 界面使用的哪些域名吗？
如果需要我尝试连接后抓一下。
下面的是正常情况访问无法进入chat 使用的地址和名称
202.89.233.101 china.bing123.com
202.89.233.100 china.bing123.com
202.89.233.96  msn-china.bing123.com

**Comment by garydak** [comment]
我手机端用的https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/lazy_group.conf他的规则，可以正常使用bing,chat功能也正常，您可以参考一下，具体怎么实现，小白我不清楚，大佬您参考参考

**Comment by Wyatt323** [comment]
目前已经实现不会跳转cn.bing.com，但是有个新的问题如下图，我看网上是说因为微软账号是国内导致的，你先去测试一下，测试完了给我反馈
![image](https://user-images.githubusercontent.com/71224625/227099306-b71af133-051e-4801-925f-dfa22ebbcb9c.png)

**Comment by Wyatt323** [comment]
搞了个新号，已成功
![image](https://user-images.githubusercontent.com/71224625/227100503-ffde4f88-e2ec-4c3b-ad58-c153ead8a26d.png)

**Comment by garydak** [comment]
我目前还是会自动跳转cn.bing.com

**Comment by Wyatt323** [comment]
清除浏览器缓存，开启域名嗅探

**Comment by garydak** [comment]
![image](https://user-images.githubusercontent.com/76925210/227145065-b1c82e79-270d-4757-826a-23446e153d72.png)
这样对吗？但是还是不行

**Comment by garydak** [comment]
还是不行，用Edge访问bing.com/new还是会自动跳转到cn.bing.com

**Comment by sukbearsuwu** [comment]
> 我手机端用的https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/lazy_group.conf他的规则，可以正常使用bing,chat功能也正常，您可以参考一下，具体怎么实现，小白我不清楚，大佬您参考参考

好像不行啊

**Comment by garydak** [comment]
![348D0043-A0A0-4A79-8043-AD9A51D2C6A7](https://user-images.githubusercontent.com/76925210/227705184-7c92adb7-55f7-4872-9a29-468a7eb21e0a.png)
如果访问还有问题，在测试规则中测bing.com，保存,添加到域名规则，指定纯净节点

**Comment by Lingchen218** [comment]
> 还是不行，用Edge访问bing.com/new还是会自动跳转到cn.bing.com

切换节点后需要删除cookie 在刷新网页就好了
