### ISSUE TITLE
开启了域名嗅探，还是会指向cn.bing.com

### ISSUE THREAD

**Issue by garydak** [Wyatt323/openclash-rules#5]
https://user-images.githubusercontent.com/76925210/227145065-b1c82e79-270d-4757-826a-23446e153d72.png
辛苦您，帮我看下是否设置还不对？是否需要在自定义中添加？

**Comment by Wyatt323** [comment]
像我这样填一下域名
![image](https://user-images.githubusercontent.com/71224625/227164218-bc279bbc-72d5-4208-9ee4-b4a5a45c944a.png)

**Comment by garydak** [comment]
好的，我再尝试一下，非常感谢您的付出！

**Comment by garydak** [comment]
还是不行，用Edge访问bing.com/new还是会自动跳转到cn.bing.com

**Comment by garydak** [comment]
1,已经拉取了最新的配置文件
![image](https://user-images.githubusercontent.com/76925210/227176604-f913c43e-b122-402b-8ab0-bd47fe34804a.png)
2，已经开启了域名嗅探
![image](https://user-images.githubusercontent.com/76925210/227176907-4c66e843-8220-4d83-87e0-f350b85cf733.png)
如何查看是否嗅探成功？目前来浏览器器还是指向cn.bing.com
3,
![image](https://user-images.githubusercontent.com/76925210/227177978-4d29c646-d6fe-4509-991c-c84ab3b3e293.png)

![image](https://user-images.githubusercontent.com/76925210/227178047-e2665364-b203-432a-9b97-d29e7ccbaf65.png)
目前是这样的
![image](https://user-images.githubusercontent.com/76925210/227178243-534f4628-7c92-4b24-9d9c-6f4137e330ea.png)
还是不行

**Comment by Wyatt323** [comment]
Yacd 控制面板的连接里面看没有嗅探到域名

**Comment by Wyatt323** [comment]
右上角搜索，搜完了还没有就再去访问一下bing再来看，还没有就是嗅探没成功
嗅探是meta内核的专属功能，使用的前提是要开启meta内核

**Comment by garydak** [comment]
![image](https://user-images.githubusercontent.com/76925210/227187761-538f965e-ae73-4a1a-a604-96755ecf191c.png)
每次尝试都有清除这个coockie
尝试打开www.bing.com/new秒进cn.bing.com

**Comment by garydak** [comment]
![image](https://user-images.githubusercontent.com/76925210/227188692-475f4c1c-3d13-406f-8b30-1593294f276e.png)

**Comment by garydak** [comment]
![image](https://user-images.githubusercontent.com/76925210/227189466-3e091451-8840-476a-a0e7-bff933d0cf33.png)

**Comment by garydak** [comment]
换了DEV 的Edg就是上图这样

**Comment by Wyatt323** [comment]
如果还没解决，那就是dns泄露造成的，强制bing.com走fallback组即可
![image](https://user-images.githubusercontent.com/71224625/227451157-fa0838d4-30e0-4492-acaf-595ce66e0b26.png)

**Comment by garydak** [comment]
![image](https://user-images.githubusercontent.com/76925210/227545120-0d1ee53b-b94c-4e63-8727-87ae90de26d8.png)
哎，还是不行，奔溃！

**Comment by garydak** [comment]
配置文件是不是有问题了，我改了设置，更新了一下策略组都不对了……
![image](https://user-images.githubusercontent.com/76925210/227549277-6a0ba364-a443-44bd-ae6a-df906e682fa9.png)

**Comment by garydak** [comment]
OK ,已经搞定，非常感谢。完美了
![image](https://user-images.githubusercontent.com/76925210/227560947-f0dda1ff-54d1-4bd6-98bd-d5da490632c9.png)
