### ISSUE TITLE
请求tubiTV抓包

### ISSUE THREAD

**Issue by sky2016cn** [Wyatt323/OpenClash-Rules#7]

**Comment by Wyatt323** [comment]
除了tubitv.com也没抓到别的域名啊，关键是我的点视频就没办法打开

**Comment by Wyatt323** [comment]
已经添加tubitv.com和tubi.video，去测试一下

**Comment by sky2016cn** [comment]
> 已经添加tubitv.com和tubi.video，去测试一下

网页没有提示非美国地区了，但是tubi 这个app添加了你的分流域名后走美国节点，还是无法播放，除非默认节点切换到美国ip ，我是想默认节点香港，tubi app走美国节点，目前还是不成功
